#!/usr/bin/env python
import os
import re
import sys

regex = re.compile(
    r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)"
)


def download(filename: str):
    """Find and Download embedded videos from URLs in the file

    Args:
        filename: Path of a file which contains URLs to find videos

    Returns:
        None
    """
    with open(filename, "r") as f:
        contents = f.read()
        matches = regex.finditer(contents)
        for match in matches:
            url = match.group()
            print(f"##### Start Downloading ({url})... #####")
            os.system(f"youtube-dl {url}")


if __name__ == "__main__":
    args = sys.argv[1:]
    for filename in args:
        download(filename)
