#!/usr/bin/env python

from os import listdir, system
from random import randint

PATH = "/Users/young/Documents/Music"


def get_playlists(filenames):
    """Return a list of M3U Playlist files

    Args:
        filenames (list): A list of files

    Returns:
        list: A list of M3U Playlist files
    """
    output = []
    for filename in filenames:
        splitted = filename.split(".")
        if splitted[-1].lower() == "m3u":
            output.append(filename)
    return output


def select_playlist(playlists):
    """Select a random playlist

    Args:
        playlists (list): A list of M3U Playlist files

    Returns:
        str: A random playlist filename
    """
    return playlists[randint(0, len(playlists)) - 1]


if __name__ == "__main__":
    playlists = get_playlists(listdir(PATH))
    todays_list = select_playlist(playlists)
    command = f"open {PATH}/{todays_list}"
    system(command)

